site_name: runrestic
repo_url: https://github.com/sinnwerkstatt/runrestic
site_url: https://sinnwerkstatt.github.io/runrestic
site_description: A wrapper script for Restic backup software that inits, creates, prunes and checks backups.
site_author: Andreas Nüßlein
edit_uri: edit/main/docs/
repo_name: sinnwerkstatt/runrestic
copyright: Maintained by <a href="https://sinnwerkstatt.com">sinnwerkstatt</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["runrestic"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sinnwerkstatt/runrestic
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/runrestic

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
